### ISSUE TITLE
Is there hooks update doc?

### ISSUE THREAD

**Issue by Cordium1990** [DeathCradle/Open-Terraria-API#100]
Some hooks have been changed. For example.
![image](https://user-images.githubusercontent.com/88142920/201454401-72ec38f4-ed96-4ebb-80d9-be8a347e1eaa.png)
This hook is no longer available. I can't find what it has changed to.

**Comment by SignatureBeef** [comment]
that hook was disabled in otapi2 (yet api exists for any unknown backwards compat), and thus excluded from otapi3. other hooks are in the wiki [here](https://github.com/SignatureBeef/Open-Terraria-API/wiki/%5Bupcoming%5D-6.-Upgrading-from-v2)

what purpose is this hook needed for? i have recently thought about exposing a similar api for terraria-only console writes but haven't had the time.

for now you would probably be looking at using a monomod runtime hook.
