### ISSUE TITLE
Load compiled assemblies (.dll) from plugin paths without resorting to wrappers.

### ISSUE THREAD

**Issue by csmir** [DeathCradle/Open-Terraria-API#133]
The aim is to build game extensions that people would welcome both in SP and MP.

Goal: Build scalable plugins for both client and server executables without having to implement wrappers that aim to achieve a different purpose, such as TSAPI. 

It does not look like this is supported. If it is not planned to be, is there a suggested route to take?

**Comment by SignatureBeef** [comment]
_Assuming im understanding you correctly:_
Ultimately it depends on what youre trying to achieve, and whether the API or code, types, assemblies (etc) you use are available on each platform.

In terms of loading a dll - OTAPI is built upon ModFramework, which inherently allows compiled .dll's to be loaded from the `./modifications` directory (amongst other more complicated techniques), so if you had both a client and server running OTAPI, this directory should fit the bill.

[Demos](https://github.com/SignatureBeef/Open-Terraria-API/tree/upcoming/examples) and [ModFramework Modules](https://github.com/SignatureBeef/ModFramework.NET) are all plugins utilising this system, however unfortunately i don't have one dedicated to demo a cross-client/server-platform scenario, but should be possible with enough care.
Refinements in this area are welcomed.

Example pic of [RuntimeExample.Server](https://github.com/SignatureBeef/Open-Terraria-API/blob/upcoming/examples/RuntimeExample.Server/MyClass.cs#L27) dropped into ./modifications in the current tshock release:
![image](https://github.com/user-attachments/assets/724c8e09-a898-4ffc-8448-57b8a67f4ef7)

**Comment by csmir** [comment]
This is precisely what I am looking for, thank you for the response.
