### ISSUE TITLE
Hook AsyncSend in NetManager.SendData

### ISSUE THREAD

**Issue by kevzhao2** [DeathCradle/Open-Terraria-API#18]
This allows us to hook and modify text sent to the client, for example.

**Comment by DeathCradle** [comment]
Not sure if required for 1.4 but hooked in https://github.com/DeathCradle/Open-Terraria-API/commit/d297cbed58972c2393941038c02306ec12df6ee0 nonetheless. Haven't had time to test correctly so feel free to reopen or submit a new issue if required.
