### ISSUE TITLE
OTAPI Client does not work at all.

### ISSUE THREAD

**Issue by EMREOYUN** [DeathCradle/Open-Terraria-API#35]
**Describe the bug**
OTAPI also included make clients with using Terraria's source code but it does not start the client because XNA Modification removes main bootable code.

**To Reproduce**

- Use OTAPI.Client.Xna solution and build client OTAPI
- Use Client Test to test the OTAPI
- Observe.

**Expected behavior**
The client should start without issues.

**Actual result**
Client can not be started because XNA method `Microsoft.Xna.Framework.Game.Run()` was removed from OTAPI due XNA modification.

***Notes:*** Client OTAPI can not be compiled without this modification. Both real Terraria and OTAPI checked with decompiler. Original one contains the boot code but OTAPI does not. Also this is not the only critical method removed from the OTAPI due the modification.

**Stack trace**
```
at OTAPI.Tests.Common.dll.GameRunner.Main  (IL offset: 0x6a)
at OTAPI.Tests.Common.dll.GameRunner.Menu  (IL offset: 0x12d)
at OTAPI.Tests.Common.dll.<>c__DisplayClass5_0.<Menu>b__0  (IL offset: 0xc)
at OTAPI.Tests.Common.dll.GameRunner.StartGame  (IL offset: 0x12)
at OTAPI.dll.WindowsLaunch.Main  (IL offset: 0x30)
at OTAPI.dll.Program.LaunchGame  (IL offset: 0xffffffff)
System.MissingMethodException: Metot bulunamadı: 'Void Microsoft.Xna.Framework.Game.Run()'.
   konum: Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   konum: Terraria.WindowsLaunch.Main(String[] args)
   konum: OTAPI.Tests.Common.GameRunner.StartGame(String[] args) \Open-Terraria-API-master\OTAPI.Tests\OTAPI.Tests.Common\GameRunner.cs içinde: satır 92
   konum: OTAPI.Tests.Common.GameRunner.<>c__DisplayClass5_0.<Menu>b__0() \Open-Terraria-API-master\OTAPI.Tests\OTAPI.Tests.Common\GameRunner.cs içinde: satır 113
   konum: OTAPI.Tests.Common.GameRunner.Menu(String[] args) \Open-Terraria-API-master\OTAPI.Tests\OTAPI.Tests.Common\GameRunner.cs içinde: satır 147
   konum: OTAPI.Tests.Common.GameRunner.Main(String[] args) \Open-Terraria-API-master\OTAPI.Tests\OTAPI.Tests.Common\GameRunner.cs içinde: satır 61
```

**Screenshots**
Not available.

**Platform and patch info (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Assembly and version you are patching: TerrariaServer 1.4.2.3
 - Version of OTAPI/git commit: latest
 - .NET runtime: .Net Framework 4.7.2

**Comment by DeathCradle** [comment]
[use otapi3 for this](https://github.com/DeathCradle/Open-Terraria-API/tree/upcoming). v2 no one ever used client stuff so it wasnt maintained over the years.
