### ISSUE TITLE
Segfault trying to "Launch modded Terraria"

### ISSUE THREAD

**Issue by drunderscore** [DeathCradle/Open-Terraria-API#39]
**Describe the bug**
A segfault occurs

**To Reproduce**
- Change base game path to `/home/james/.steam/steam/steamapps/common/Terraria/`
- Install OTAPI
- Remove `csharp/plugins/modules/otapi-runtime/HostGamePlugin.cs` (required due to #38)
- Launch OTAPI

**Expected behavior**
The game to launch, modded with OTAPI

**Stack trace**
No stack trace available, this is a segfault. ~~GDB provides no relevant output, but if you think it does I can provide it.~~ i lied
[output before segfault](https://paste.gg/p/anonymous/c5bd08400a904264886453fa552aa8a8)
GDB backtrace:
```
0x00007ffff7b7da0e in __strcmp_avx2 () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7b7da0e in __strcmp_avx2 () at /usr/lib/libc.so.6
#1  0x00007ffff4bc157d in OPENGL_PrepareWindowAttributes () at /home/james/otapi/bin/Release/net5.0/ubuntu.16.04-x64/publish/lib64/libFNA3D.so.0
#2  0x00007ffff4bbf4d1 in FNA3D_PrepareWindowAttributes () at /home/james/otapi/bin/Release/net5.0/ubuntu.16.04-x64/publish/lib64/libFNA3D.so.0
#3  0x00007fff81e0289e in  ()
#4  0x0000000004254e45 in  ()
#5  0x00007ffff74f9848 in  () at /home/james/otapi/bin/Release/net5.0/ubuntu.16.04-x64/publish/libcoreclr.so
#6  0x00007fffffffd080 in  ()
#7  0x0000000000000000 in  ()
```

**Platform and patch info (please complete the following information):**
 - OS: `Linux JAMES-DESKTOP 5.10.41-1-MANJARO #1 SMP PREEMPT Fri May 28 19:10:32 UTC 2021 x86_64 GNU/Linux`
 - Assembly and version you are patching: `Terraria Server v1.4.2.3`
 - Version of OTAPI/git commit: `318aec0`
 - .NET runtime: `5.0.203

**Comment by DeathCradle** [comment]
As stated in #38, the hostgame module is certainly required, the root cause is because [linux is still in the works](https://github.com/DeathCradle/Open-Terraria-API/projects/2). The Linux launcher is currently available to download due to it being the same workflow as the other platforms (sorry, but easier to do this for my own testing too)
