### ISSUE TITLE
OTAPI v3 - Client Index doesn't get passed into SendBytesEventArgs

### ISSUE THREAD

**Issue by Moneylover3246** [DeathCradle/Open-Terraria-API#57]
**Describe the bug**
The SendBytes hook doesn't pass the client's index into its arguments

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/66443019/148665640-0c297cdf-0848-45b2-90e1-cde6d6bc2ecb.png)

**Platform and patch info**
 - OS: Windows
 - Assembly and version you are patching: TerrariaServer v1.4.3.2
 - Version of OTAPI/git commit: c6bd0df3d04571e3b58172b8f1d930d750b62350
 - .NET runtime: NET 6

**Comment by DeathCradle** [comment]
should be passed in 5f9dcbd
