### ISSUE TITLE
OTAPIv3 PC; Nuget package: outdated/incorrect dependencies.

### ISSUE THREAD

**Issue by 0x3fcf1bbd** [DeathCradle/Open-Terraria-API#67]
The OTAPI.Upcoming nuget packages 3.0.37-alpha reference dependencies:
```
ModFramework (>= 1.0.39-alpha)
MonoMod (>= 22.3.23.4)
MonoMod.RuntimeDetour (>= 22.3.23.4) 
```
but ships binaries that are built against updated ones from 6596b5b:
```
ModFramework 1.0.40-alpha
MonoMod 22.5.1.1
MonoMod.RuntimeDetour 22.5.1.1
```
therefore requiring consumers to manually install the updated dependencies.

**Comment by SignatureBeef** [comment]
Should be sorted as of 3.0.40-alpha where automation of nuget dependencies should be implemented.
